# Generated by Django 3.2.4 on 2021-06-28 18:32

from django.db import migrations, models
import pacientes.models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=pacientes.models.imagens_perfil),
        ),
    ]
